package com.wsy.webseed.dao.entity;

// Generated 2015-10-13 17:16:11 by Hibernate Tools 4.0.0

import javax.persistence.*;
import java.util.Date;

/**
 * SysRole generated by hbm2java
 */
@Entity
@Table(name = "sys_role")
public class SysRole implements java.io.Serializable {

	private int id;

	private String name;

	private boolean isBuiltin;

	private Date updateTime;

	private Date createTime;


	public SysRole() {
	}

	public SysRole(int id, String name, boolean isBuiltin, Date updateTime,
			Date createTime) {
		this.id = id;
		this.name = name;
		this.isBuiltin = isBuiltin;
		this.updateTime = updateTime;
		this.createTime = createTime;
	}

	public SysRole(String name, boolean isBuiltin, Date updateTime,
			Date createTime) {
		this.name = name;
		this.isBuiltin = isBuiltin;
		this.updateTime = updateTime;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, unique = true, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "is_builtin", nullable = false)
	public boolean isIsBuiltin() {
		return this.isBuiltin;
	}

	public void setIsBuiltin(boolean isBuiltin) {
		this.isBuiltin = isBuiltin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 22)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 22)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}



}
